# Generated by Django 2.2.28 on 2022-12-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_puertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.BigIntegerField()),
            ],
        ),
    ]
